---
# file: main.yml

- name: pause
  pause: 
    minutes: "2"

# Deploy Service mesh operator
- name: Service mesh operator
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    src: "{{ role_path }}/files/servicemesh.yaml"