---
# file: main.yml

# Deploy the Openshift Serverless Opeartor

- name: Deploy Openshift Serverless Operator
  shell: oc apply -f {{ role_path }}/files/serverlessoperator.yaml
  ignore_errors: no

# Wait for the operator to be deployed before moving on to creating the Knative serving namespace and crd
#- name: Is the Knative serving Operator deployed?
#  shell: oc get subscription serverless-operator -n openshift-operators -o jsonpath="{.status.catalogHealth[0].healthy}"
#  register: serverless
#  until: serverless.stdout.find("true") != -1
#  retries: 150
#  delay: 15

# Create the Knative serving namespace and KnativeServing CRD
- name: Create Knative serving namespace
  shell: oc apply -f {{ role_path }}/files/knativenamespace.yaml

# Create the Knative serving namespace and KnativeServing CRD
- name: Create Knative serving CRD
  shell: oc apply -f {{ role_path }}/files/serving.yaml
  retries: 20
  delay: 5

# Wait for Knative serving to be ready before continuing
- name: Is Knative servering deployed?
  shell: oc get knativeserving.operator.knative.dev/knative-serving -n knative-serving -o jsonpath="{.status.conditions[3].status}"
  register: knative
  until: knative.stdout.find("True") != -1
  retries: 400
  delay: 5
