apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: taskwatch
spec:
  steps:
    - name: watchfetch
      image: quay.io/ilawson/oconline
      command:
        - curl
      args:
        - "https://raw.githubusercontent.com/utherp0/workshop4/master/attendee/tekton/watch.sh"
        - ">"
        - "watch.sh" 
    - name: watchsetperm
      image: quay.io/ilawson/oconline
      command:
        - chmod
      args:
        - "700"
        - "watch.sh"
    - name: watchwait
      image: quay.io/ilawson/oconline
      command:
        - /bin/bash
      args:
        - "watch.sh"