---
# file: main.yml

# Deploy Knative Eventing - currently using community operator
- name: Deploy Openshift Serverless Eventing Operator
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    src: "{{ role_path }}/files/amqstreamsoperator.yaml"