apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemesh
  namespace: openshift-operators
spec:
  channel: "1.0"
  name: servicemesh-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace