---
# file: main.yml

# Deploy Elastic search operator
- name: Deploy Elastic search operator
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    src: "{{ role_path }}/files/elasticsearch.yaml"

# Deploy Jaeger operator
- name: Deploy Jaeger operator
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    src: "{{ role_path }}/files/jaeger.yaml"    

# Deploy Kiali operator
- name: Deploy Kiali operator
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    src: "{{ role_path }}/files/kiali.yaml"

- name: pause
  pause: 
    minutes: "2"

# Deploy Service mesh operator
- name: Service mesh operator
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    src: "{{ role_path }}/files/servicemesh.yaml"